//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messanger.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class Room
    {
        public int Id { get; set; }
        public Nullable<int> user1_id { get; set; }
        public Nullable<int> user2_id { get; set; }

        public static List<Room> GetRooms(string roomNumbers,DatabaseEntities1 db)
        {
            var numbersStr = roomNumbers.Split(',');
            List<Room> rooms = new List<Room>();
            foreach(string number in numbersStr)
            {
                int room_id = Convert.ToInt32(number);
                rooms.Add(db.Room.FirstOrDefault(x=>x.Id == room_id));
            }
            return rooms;
        }
    }
}
